name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - uses: actions/checkout@v3

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Build release binary
        run: cargo build --release

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: commitz-${{ matrix.os }}
          path: target/release/commitz*

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: commitz-ubuntu-latest
          path: .
      - uses: actions/download-artifact@v4
        with:
          name: commitz-macos-latest
          path: .
      - uses: actions/download-artifact@v4
        with:
          name: commitz-windows-latest
          path: .

      - name: Upload to GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: commitz*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
